# sudo docker build -t behavior_sequence_pre_training .
# sudo docker run -it --gpus all behavior_sequence_pre_training bash

# sudo docker tag fd2a23e7b9c5 iamlxb3/behavior_sequence_pre_training_via_mtc
# sudo docker push iamlxb3/behavior_sequence_pre_training_via_mtc

# rm -rf /behavior_sequence_pre_training/app/downstream_tasks/results/*

FROM iamlxb3/cuda_9.0_cudnn7_py3.6_ubuntu16.04
# FROM nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04

# # RUN apk update && apk add bash
RUN pip3 install --upgrade pip
RUN pip3 install torch==1.4.0
RUN pip3 install transformers==3.3.0
RUN pip3 install numpy==1.19.4
RUN pip3 install ipdb==0.12
RUN pip3 install h5py==2.10.0
RUN pip3 install tqdm==4.46.0
RUN pip3 install pytorch_lightning==1.1.1
RUN pip3 install pandas==0.24.1
RUN pip3 install easydict==1.9
RUN pip3 install scikit-learn==0.22
RUN pip3 install dill==0.3.1.1
RUN pip3 install textdistance==4.2.0
RUN pip3 install compress_pickle==2.0.1
RUN pip3 install captum==0.2.0

ADD . /behavior_sequence_pre_training

WORKDIR /behavior_sequence_pre_training/game_seq_embedder/
RUN python3.6 setup.py install

WORKDIR /behavior_sequence_pre_training/app